#
#	This file is part of the OrangeFox Recovery Project
# 	Copyright (C) 2020-2026 The OrangeFox Recovery Project
#
#	OrangeFox is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	any later version.
#
#	OrangeFox is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
# 	This software is released under GPL version 3 or any later version.
#	See <http://www.gnu.org/licenses/>.
#
# 	Please maintain this if you use this script or any part of it
#

# vendorsetup.sh — OrangeFox build variables for Pixel (Tensor G3/G4) Pixel family.
# This script is sourced by the OrangeFox build system after `lunch twrp_pixels-eng`.
# It exports all FOX_*, OF_*, TW_* environment variables that control the build,
# and cross-compiles the LGZ compressor/decompressor binaries.
#
# FDEVICE must match the lunch target suffix and directory name under device/google/.
# Runtime device detection (shiba/husky/akita) is done in runatboot.sh via ro.hardware.

FDEVICE="pixels"

fox_get_target_device() {
chkdev=$(echo "$BASH_SOURCE" | grep -w $FDEVICE)
   if [ -n "$chkdev" ]; then
      FOX_BUILD_DEVICE="$FDEVICE"
   else
      chkdev=$(set | grep BASH_ARGV | grep -w $FDEVICE)
      [ -n "$chkdev" ] && FOX_BUILD_DEVICE="$FDEVICE"
   fi
}

if [ -z "$1" -a -z "$FOX_BUILD_DEVICE" ]; then
   fox_get_target_device
fi

if [ "$1" = "$FDEVICE" -o "$FOX_BUILD_DEVICE" = "$FDEVICE" ]; then

# --- Platform selection ---
if [ -n "${DEVICE_BUILD_FLAG:-}" ]; then
    echo ""
    echo "=============================================="
    echo "  DEVICE_BUILD_FLAG already set: $DEVICE_BUILD_FLAG"
    echo "  Skipping interactive menu."
    echo "=============================================="
else
echo ""
echo "=============================================="
echo "  Select target platform:"
echo "  1) zuma    (Tensor G3: Pixel 8/8 Pro/8a)"
echo "  2) zumapro (Tensor G4: Pixel 9/9 Pro/9 Pro XL/9a)"
echo "  3) gs201   (Tensor G2: Pixel 7/7 Pro/7a)"
echo "  4) gs101   (Tensor G1: Pixel 6/6 Pro/6a) [WIP]"
echo "  5) laguna  (Tensor G5: Pixel 10/10 Pro/10 Pro XL)"
echo "=============================================="
printf "  Choice [1/2/3/4/5] (timeout 15s): "
if read -t 15 _platform_choice 2>/dev/null; then
    case "$_platform_choice" in
        2) export DEVICE_BUILD_FLAG="zumapro" ;;
        3) export DEVICE_BUILD_FLAG="gs201" ;;
        4) export DEVICE_BUILD_FLAG="gs101" ;;
        5) export DEVICE_BUILD_FLAG="laguna" ;;
        *) export DEVICE_BUILD_FLAG="zuma" ;;
    esac
else
    echo ""
    export DEVICE_BUILD_FLAG="zuma"
    echo "  Timeout — defaulting to zuma"
fi
fi
echo "=============================================="
echo "  Building for platform: $DEVICE_BUILD_FLAG"
echo "=============================================="

# --- Generate .build_platform.conf for build scripts (fox_build_callback.sh etc.) ---
# Environment variables don't survive make/ninja recipe shells reliably,
# so we persist the platform choice to a file that scripts can source.
_conf_file="$(gettop)/device/google/pixels/.build_platform.conf"
cat > "$_conf_file" <<_PLATFORM_EOF
# Auto-generated by vendorsetup.sh — DO NOT EDIT
# Re-generated on every lunch / vendorsetup.sh source
# Sourced by fox_build_callback.sh and other build scripts
PLATFORM=${DEVICE_BUILD_FLAG}
_PLATFORM_EOF
echo "  Wrote $_conf_file"

# --- Version & Build ---
export FOX_BUILD_TYPE=Stable
export FOX_VARIANT=default
export OF_MAINTAINER=LeeGarChat
export USE_CCACHE="1"
export TARGET_ARCH="arm64"
export LC_ALL="C"

# --- Device type ---
export FOX_VIRTUAL_AB_DEVICE=1
export FOX_AB_DEVICE=1
export FOX_VENDOR_BOOT_RECOVERY=1
if [ "$DEVICE_BUILD_FLAG" = "gs201" ] || [ "$DEVICE_BUILD_FLAG" = "gs101" ]; then
    export FOX_RECOVERY_VENDOR_BOOT_PARTITION="/dev/block/platform/14700000.ufs/by-name/vendor_boot"
elif [ "$DEVICE_BUILD_FLAG" = "laguna" ]; then
    export FOX_RECOVERY_VENDOR_BOOT_PARTITION="/dev/block/platform/3c400000.ufs/by-name/vendor_boot"
else
    export FOX_RECOVERY_VENDOR_BOOT_PARTITION="/dev/block/platform/13200000.ufs/by-name/vendor_boot"
fi

# --- Vanilla build (non-Xiaomi device, skip MIUI patches) ---
export FOX_VANILLA_BUILD=1
export OF_DISABLE_MIUI_SPECIFIC_FEATURES=1

# --- Multi-device support ---
if [ "$DEVICE_BUILD_FLAG" = "zumapro" ]; then
    export TARGET_DEVICE_ALT="tokay,caiman,comet,komodo,tegu"
    export FOX_TARGET_DEVICES="tokay,caiman,comet,komodo,tegu"
elif [ "$DEVICE_BUILD_FLAG" = "gs201" ]; then
    export TARGET_DEVICE_ALT="panther,cheetah,lynx,tangorpro,pantah"
    export FOX_TARGET_DEVICES="panther,cheetah,lynx,tangorpro,pantah"
elif [ "$DEVICE_BUILD_FLAG" = "gs101" ]; then
    export TARGET_DEVICE_ALT="oriole,raven,bluejay"
    export FOX_TARGET_DEVICES="oriole,raven,bluejay"
elif [ "$DEVICE_BUILD_FLAG" = "laguna" ]; then
    export TARGET_DEVICE_ALT="blazer,mustang,frankel,rango,deepspace"
    export FOX_TARGET_DEVICES="blazer,mustang,frankel,rango,deepspace"
else
    export TARGET_DEVICE_ALT="shiba,husky,akita,shusky"
    export FOX_TARGET_DEVICES="shiba,husky,akita,shusky"
fi
# --- OrangeFox UI ---
# OF_SCREEN_H is the compile-time DEFAULT screen height for theme scaling.
# Devices with different screen heights (e.g. husky=2244) override this at
# runtime via the DOF_SCREEN_H property set in runatboot.sh → data.cpp reads it.
export OF_SCREEN_H=2400
if [ "$DEVICE_BUILD_FLAG" = "zumapro" ]; then
    export OF_STATUS_H=150
elif [ "$DEVICE_BUILD_FLAG" = "gs201" ]; then
    export OF_STATUS_H=130
elif [ "$DEVICE_BUILD_FLAG" = "gs101" ]; then
    export OF_STATUS_H=130
elif [ "$DEVICE_BUILD_FLAG" = "laguna" ]; then
    export OF_STATUS_H=150
else
    export OF_STATUS_H=130
fi
export OF_STATUS_INDENT_LEFT=80
export OF_STATUS_INDENT_RIGHT=80
export OF_HIDE_NOTCH=1
export OF_CLOCK_POS=1
export OF_ALLOW_DISABLE_NAVBAR=0
export OF_OPTIONS_LIST_NUM=6

# --- Compression ---
export OF_USE_LZ4_COMPRESSION=1

# --- Feature flags ---
export OF_IGNORE_LOGICAL_MOUNT_ERRORS=1
export OF_NO_TREBLE_COMPATIBILITY_CHECK=1
export OF_ENABLE_LPTOOLS=1
export OF_USE_GREEN_LED=0
export OF_NO_SPLASH_CHANGE=1
export OF_RECOVERY_AB_FULL_REFLASH_RAMDISK=1

# --- dm-crypt teardown before /data format (metadata encryption) ---
# Without this, /dev/block/mapper/userdata stays open after unmount,
# and make_f2fs fails with "Error: In use by the system!" on the raw device.
# Uses AOSP dmctl (built from source) — preferred over prebuilt dmsetup.
export OF_USE_DMCTL=1

# --- Flashlight (Pixel 8: LM3644 torch via I2C, controlled by script) ---
export OF_FL_PATH1="cmd:/system/bin/torch_ctl.sh"

# --- Encryption (FBE metadata decryption via Trusty TEE KeyMint) ---
# Do not force legacy Keymaster on Tensor 3. Recovery must use AIDL KeyMint.
unset OF_DEFAULT_KEYMASTER_VERSION
# export OF_DEFAULT_KEYMASTER_VERSION="4.1"
# OF_SKIP_FBE_DECRYPTION is controlled in BoardConfig during staged bring-up.


# --- Binaries & Tools ---
export FOX_REPLACE_TOOLBOX_GETPROP=1
export FOX_USE_BASH_SHELL=1
export FOX_BASH_TO_SYSTEM_BIN=1
# export FOX_ASH_IS_BASH=1
# export FOX_USE_TAR_BINARY=1
# export FOX_USE_SED_BINARY=1
# export FOX_USE_XZ_UTILS=1
# export FOX_USE_LZ4_BINARY=1
# export FOX_USE_ZSTD_BINARY=1
# export FOX_USE_UPDATED_MAGISKBOOT=1
# export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=1

# --- App & Features ---
export FOX_ENABLE_APP_MANAGER=1
export FOX_DELETE_AROMAFM=1

# --- Storage ---
export OF_QUICK_BACKUP_LIST="/boot;/vendor_boot;/data;"
export OF_UNBIND_SDCARD_F2FS=1
export OF_BIND_MOUNT_SDCARD_ON_FORMAT=1
if [ "$DEVICE_BUILD_FLAG" = "zumapro" ] || [ "$DEVICE_BUILD_FLAG" = "laguna" ]; then
    export OF_DYNAMIC_FULL_SIZE=12884901888
else
    export OF_DYNAMIC_FULL_SIZE=8531214336
fi

# --- Battery ---
export OF_USE_LEGACY_BATTERY_SERVICES=1

# --- Logging ---
export OF_DONT_KEEP_LOG_HISTORY=0
export FOX_INSTALLER_DISABLE_AUTOREBOOT=0
export FOX_USE_DATA_RECOVERY_FOR_SETTINGS=0


# --- KernelSU ---
export FOX_ENABLE_KERNELSU_SUPPORT=1
export FOX_ENABLE_KERNELSU_NEXT_SUPPORT=1

# --- Size reduction: theme/font cleanup handled in fox_build_callback.sh ---
export FOX_DELETE_INITD_ADDON=1

# --- Custom UI callback: overlay fox_mod_ui XMLs over default pages during build ---
export FOX_LOCAL_CALLBACK_SCRIPT="$(gettop)/device/google/pixels/fox_build_callback.sh"

# --- LGZ v3: cross-compile compressor/decompressor ---
# Uses 7zip LZMA SDK sources from external/lzma/C/ — no external liblzma dependency.
LGZ_SRC_DIR="$(gettop)/device/google/pixels/selfcode/lgz"
LGZ_SRC_FILE="$LGZ_SRC_DIR/lgzv3.c"
LZMA_DIR="$(gettop)/external/lzma/C"
LZMA_SRCS="$LZMA_DIR/Alloc.c $LZMA_DIR/LzFind.c $LZMA_DIR/LzmaDec.c $LZMA_DIR/LzmaEnc.c $LZMA_DIR/Lzma2Dec.c $LZMA_DIR/Lzma2Enc.c $LZMA_DIR/CpuArch.c"
LZMA_CFLAGS="-I$LZMA_DIR -D_7ZIP_ST -O3 -pipe -fopenmp -flto"
if [ -f "$LGZ_SRC_FILE" ]; then
    echo "[LGZ] Cross-compiling lgz v3 binaries..."
    # Host binary (for build-time compression with OpenMP + LTO)
    if ! [ -x "$LGZ_SRC_DIR/lgz_host_bin" ]; then
        echo "[LGZ]   Compiling host binary (lgzv3, -O3 -fopenmp -flto)..."
        gcc $LZMA_CFLAGS -march=native -mtune=native \
            -o "$LGZ_SRC_DIR/lgz_host_bin" "$LGZ_SRC_FILE" $LZMA_SRCS 2>&1
        if [ $? -eq 0 ]; then
            echo "[LGZ]   Host binary OK: $LGZ_SRC_DIR/lgz_host_bin"
        else
            echo "[LGZ]   ERROR: Host compilation failed."
        fi
    else
        echo "[LGZ]   Host binary already exists, skipping."
    fi
    # ARM64 static binary (for device — placed in ramdisk by fox_build_callback.sh)
    # Uses AOSP prebuilt clang + musl sysroot (no external cross-toolchain needed)
    if ! [ -f "$LGZ_SRC_DIR/lgz_device" ]; then
        echo "[LGZ]   Cross-compiling ARM64 static binary (lgzv3)..."
        CLANG="$(gettop)/prebuilts/clang/host/linux-x86/clang-r510928/bin/clang"
        MUSL_SYSROOT="$(gettop)/prebuilts/build-tools/sysroots/aarch64-unknown-linux-musl"
        if [ -x "$CLANG" ] && [ -d "$MUSL_SYSROOT" ]; then
            "$CLANG" --target=aarch64-unknown-linux-musl \
                --sysroot="$MUSL_SYSROOT" --rtlib=compiler-rt \
                -static -O2 -I"$LZMA_DIR" -D_7ZIP_ST \
                -o "$LGZ_SRC_DIR/lgz_device" "$LGZ_SRC_FILE" $LZMA_SRCS 2>&1
            if [ $? -eq 0 ]; then
                echo "[LGZ]   ARM64 binary OK: $LGZ_SRC_DIR/lgz_device"
            else
                echo "[LGZ]   ERROR: ARM64 cross-compilation failed."
            fi
        else
            echo "[LGZ]   ERROR: AOSP clang or musl sysroot not found."
            echo "[LGZ]   Expected: $CLANG"
            echo "[LGZ]   Sysroot:  $MUSL_SYSROOT"
        fi
    else
        echo "[LGZ]   ARM64 binary already exists, skipping."
    fi
fi

    export | grep "FOX"
    export | grep "OF_"
    export | grep "TARGET_"
    export | grep "TW_"
	# let's see what are our build VARs
	if [ -n "$FOX_BUILD_LOG_FILE" -a -f "$FOX_BUILD_LOG_FILE" ]; then
  	   export | grep "FOX" >> $FOX_BUILD_LOG_FILE
  	   export | grep "OF_" >> $FOX_BUILD_LOG_FILE
   	   export | grep "TARGET_" >> $FOX_BUILD_LOG_FILE
  	   export | grep "TW_" >> $FOX_BUILD_LOG_FILE
 	fi
fi
